const { exec } = require("child_process");
const { performance } = require("perf_hooks");

const removeClientFilesFromCContainer = require("./removeClientFilesFromCContainer.js");
const copyClientFilesToCContainer = require("./copyClientFilesToCContainer.js");
const isFatalGCCWarning = require("../util/isFatalGCCWarning.js");

const compileSubmission = (req, socketInstance) => {
	return new Promise((resolve, reject) => {
		let compilationTime = performance.now();
		/*
		 * @resolve
		 * Always resolve the stdout as resolve(stdout)
		 *
		 * @reject
		 * Reject the error and stderr values as keys in a JSON object ...
		 * ... that is, as reject({ error }) and reject({ stderr })
		 * This is because when catching rejections with .catch(error) in ...
		 * ... dockerConfigController's functions, we can see if the caught error ...
		 * ... is an error or an stderr with if (error.error) and if (error.stderr)
		 */
		try {
			const { socketId } = req.body;
			const containerName = socketId;
			const submissionFileName = `${socketId}.c`;

			console.log(
				`Compiling user's submission in container ${containerName}...`
			);
			socketInstance.instance.to(socketId).emit("docker-app-stdout", {
				stdout: `Compiling user's submission...`,
			});
			/*
			 * Flags used in compilation:
			 * -Wall: enables some warnings
			 * -Wfatal-errors: stops compilation after a fatal error has occurred
			 * -Werror=div-by-zero: stops compilation for a div-by-zero warning, so ...
			 * ... division by zero is now a compilation error
			 *
			 * check more GCC warning options: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
			 */
			exec(
				`docker exec -i ${containerName} gcc ${submissionFileName} -o submission -Wall -Wfatal-errors -Werror=div-by-zero`,
				(error, stdout, stderr) => {
					compilationTime = performance.now() - compilationTime;
					// compilation error is received as error as well as an stderr
					if (stderr) {
						console.error(
							`stderr while compiling submission inside container ${containerName}:`,
							stderr
						);
						/*
						 * stderr may also be a non-fatal warning generated by GCC, like ...
						 * stderr while compiling submission inside container s-6353b6540a377d1610:
						 * s-6353b6540a377d1610.c: In function 'main':
						 * s-6353b6540a377d1610.c:5:1: warning: implicit declaration of function 'foo' [-Wimplicit-function-declaration]
						 *  foo();
						 *  ^~~
						 *
						 * In such a case, resolve stderr as stdout
						 * However, if stderr is not a warning, or if it is fatal, ...
						 * ... reject the stderr
						 */
						//  check if stderr is a warning
						const { isWarning, isFatalWarning } = isFatalGCCWarning(
							stderr,
							socketId
						);
						if (isWarning && !isFatalWarning) {
							socketInstance.instance
								.to(socketId)
								.emit("docker-app-stdout", {
									stdout: `warning while compiling submission: ${stderr}`,
								});
							// if the warning is not fatal, resolve the warning
							return resolve({
								warning: stderr,
								compilationTime,
							});
						} else {
							// this block executes if the warning is fatal or if there's ...
							// ... no warning in the stderr
							socketInstance.instance
								.to(socketId)
								.emit("docker-app-stdout", {
									stdout: `stderr while compiling submission: ${stderr}`,
								});
							return reject({
								stderr,
								errorType: "compilation-error",
								compilationTime,
							});
						}
					} else if (error) {
						console.error(
							`error while compiling submission inside container ${containerName}:`,
							error
						);
						socketInstance.instance
							.to(socketId)
							.emit("docker-app-stdout", {
								stdout: `error while compiling submission`,
							});

						return reject({ error });
					}
					if (stdout.trim() !== "") {
						console.log(
							`stdout while compiling submission inside container ${containerName}: ${stdout}`
						);
						socketInstance.instance
							.to(socketId)
							.emit("docker-app-stdout", {
								stdout: `stdout while compiling submission: ${stdout}`,
							});
					}
					socketInstance.instance
						.to(socketId)
						.emit("docker-app-stdout", {
							stdout: `User's submission compiled`,
						});
					return resolve({ stdout, compilationTime });
				}
			);
		} catch (error) {
			console.log(`error during compileInCContainer: ${error}`);
			return reject({ error });
		}
	});
};

module.exports = (req, socketInstance) => {
	return new Promise((resolve, reject) => {
		removeClientFilesFromCContainer(req.body.socketId)
			.then(() => copyClientFilesToCContainer(req, socketInstance))
			.then(stdout => {
				return compileSubmission(req, socketInstance);
			})
			.then(stdout => {
				return resolve(stdout);
			})
			.catch(error => {
				// return reject(error) and not reject({ error }) because ...
				// ... at this point, error is already an object
				return reject(error);
			});
	});
};
